### ISSUE TITLE
Don't make a blind copy!

### ISSUE THREAD

**Issue by bvaudour** [KaOS-Community-Packages/palemoon#1]
1. Please read http://kaosx.us/kcp-guide/ and http://kaosx.us/packaging-guide/
2. The pkgname and the name of the name of the repo have to be same.
3. Check the errors with pckcp.

**Comment by demmm** [comment]
Since this package is actively maintinaed and on the list of packages to be removed, a warning here how to fix it.
The description line can't be empty, kcp and octopi will fail to read it correctly, see the KCP Guide how to start a package correctly.
Now make sure that the line showing `No description or website provided. — Edit is fixed
